--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ElectroGamesYT/BankUI
build-by-default: true
branches:
- main
projects:
  BankUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^2.1
...
