main : Electro\BankUI\BankUI
name: BankUI
version: 2.0.0
api: 3.0.0
Author: Electro
depend: ["EconomyAPI"]

commands:
  bank:
    description: Opens The BankUI
    
permissions:
  bankui.admin:
    description: Permission to manage other Players banks
    default: op
